### ISSUE TITLE
Color detection when using PM2

### ISSUE THREAD

**Issue by RobinTail** [webdiscus/ansis#19]
Hello @webdiscus ,

## Feature request

**What is motivation or use case for adding/changing the behavior?**

I found out that color detection does not work when running an application using [PM2](https://pm2.keymetrics.io/docs/usage/quick-start/) process manager.
I managed to debug it to the line https://github.com/webdiscus/ansis/blob/9f78e35ede2aa292c9d3256a8a5de3f104fabe43/src/color-support.js#L47

The reason is that `process.stdout` does not have `isTTY` property.
https://github.com/webdiscus/ansis/blob/9f78e35ede2aa292c9d3256a8a5de3f104fabe43/src/color-support.js#L124

PM2 uses log files to write the process output and the colors support depends on the terminal used.

So, despite following `process.env` variables colors do not appear:

```
COLORTERM: 'truecolor',
LC_TERMINAL: 'iTerm2',
TERM: 'xterm-256color',
```

**Describe the solution you'd like**

I'd like to request an exception for PM2 case that can be identified by the following two `process.env` variables:

```ts
const isPM2 = "PM2_HOME" in env && "pm_id" in env;
```

So that the line 47 could look this way:

```ts
if ((!isTTY && !isPM2) || /-mono|dumb/i.test(term)) return SPACE_MONO;
```

Then this statement would be skipped for PM2 case and the actual terminal would be detected.

**Describe alternatives you've considered**

I tried using `FORCE_COLOR` env — it works, but since I'm actually developing a library for consumer applications, I'd like to avoid that. I also tried the PM2 detection approach inside by library that is using `ansis`, but it can not work because `getColorSpace()` is executed immediately after import, so I can not alter `process.env` in advance from the library I work on.

However, I'm open to any suggestions and discussions in this regard.
What do you think, @webdiscus ?

**Comment by webdiscus** [comment]
Hello @RobinTail 

thanks for the feature request.
I will add the supports for PM2.

How many colors does PM2, truecolor, 256, 16 support?

**Comment by RobinTail** [comment]
It should depend on the actual terminal, meaning that the lines AFTER the line 47 (`isTTY` condition) should be executed

https://github.com/webdiscus/ansis/blob/9f78e35ede2aa292c9d3256a8a5de3f104fabe43/src/color-support.js#L49-L69

Basically, the lack of `isTTY` should be ignored when PM2 is detected, @webdiscus

**Comment by RobinTail** [comment]
I know that the size of `ansis` is important for you, so I'm not pushing for any particular implementation, @webdiscus 
Therefore, I just want to convey the idea that `isTTY` is missing in PM2 case, but the actual terminal can still support colors.

**Comment by RobinTail** [comment]
Or, maybe there can be an exception made here, @webdiscus 

```ts
 const isTTY = isNextJS || isPM2 || (isDeno ? Deno.isatty(1) : stdout && 'isTTY' in stdout); 
```

**Comment by RobinTail** [comment]
I collected all my suggestions and ideas in PR #20 , including tests, @webdiscus .
I tested it manually on my machine using local build and linked references.
And it works.

**Comment by webdiscus** [comment]
> I know that the size of `ansis` is important for you

This is important not so much for me as for the developers who compare many libs and one of the most important criterion is the size :-)

But your implementation in PR, byte by byte, is perfect! Thank You so much!

I will publish new package now.

**Comment by webdiscus** [comment]
@RobinTail 

The version `3.1.0` has been released with PM2 support.
Thanks!
