### ISSUE TITLE
[BUG] 1.3.5 seems broken

### ISSUE THREAD

**Issue by nicholasio** [webdiscus/ansis#2]
**Describe the bug**

It looks like the recently released version (1.3.5) is broken. The published package.json points to `src/index.js` while the published code lives in the dist directory.

![image](https://user-images.githubusercontent.com/6104632/165567581-8c0082d5-11d2-4384-b42a-12137b9ce9d4.png)

This is probably breaking a bunch of packages that depends on this package.
![image](https://user-images.githubusercontent.com/6104632/165569085-55943ec6-a661-40e9-b848-fb2680e00474.png)

**To Reproduce**
If issue is small you can add the code block to commentary.
Preferably, create a bug repository with reproducible problems.

**Expected behavior**

**Dev Environment (please complete the following information):**
 - OS: [e.g. macOS / Windows 10 / Ubuntu 18]
 - Node [e.g. 12 LTS, 14, 16.04]

**Additional context**

**Comment by nicholasio** [comment]
@webdiscus Prob a good idea to deprecate 1.3.5 so that projects don't auto-update to 1.3.5 while a final fix is released.

**Comment by aotarola** [comment]
I did auto-update the dependency, and got the error as well 😢

**Comment by webdiscus** [comment]
@nicholasio,

Thanks for the report.

I am researching the problem.
I'm trying to fix it as quickly as possible.

**Comment by webdiscus** [comment]
# Thanks everyone for the quick bug report!

The corrupted version `1.3.5` is deprecated.
Please use the stable version `1.3.4`.

I just updated the single README.md file today and NPM has corrupted the package. Very, very sad :-/

Today NPM services were very buggy:
- generates incorrect links to images from github in README.md
- missing/broken packages.json

What happened with NPM tooday?

**Comment by webdiscus** [comment]
> @webdiscus Prob a good idea to deprecate 1.3.5 so that projects don't auto-update to 1.3.5 while a final fix is released.

Thank you! The broken version `1.3.5` is deprecated.

**Comment by nicholasio** [comment]
@webdiscus Thanks! Appreciate the quick turnaround.

**Comment by webdiscus** [comment]
Note: I have bumped the latest stable version `1.3.4` to number `1.3.6` instead of the deprecated broken version `1.3.5`.

**Comment by webdiscus** [comment]
> I did auto-update the dependency, and got the error as well 😢

The fixed version is `1.3.6`.

**Comment by webdiscus** [comment]
> +1

The fixed version is `1.3.6`.
