### ISSUE TITLE
isSupported() return false in Cloudflare Worker

### ISSUE THREAD

**Issue by louisgv** [webdiscus/ansis#24]
## Current behaviour

When using ansis in a CloudFlare wrangler workrer, ansis.isSupported() returns false

## Expected behaviour

It should return true locally and render color

### Reproduction Example

ansis + cloudflare worker: https://workers.cloudflare.com/

## Environment

- OS (inc. version): macOS
- version of Node.js: 20.x
- version of the Plugin: 3.3.2

## Appreciation for the useful project

- [ ] After the problem is resolved, do not forget to give a star ⭐

**Comment by webdiscus** [comment]
Hello @louisgv,

thanks for the issue. I will add Cloudflare Worker detection.

**Comment by webdiscus** [comment]
@louisgv,

## We have a problem

There is no **save way** to detect Cloudflare Worker (CFW) Runtime.
[How to detect the Cloudflare Worker runtime?](https://community.cloudflare.com/t/how-to-detect-the-cloudflare-worker-runtime/293715)

There are no ENV variables in CWF to determine whether an output is supported.  All others CLI environments contains own variables, for example:
- Azure - `TF_BUILD`
- GitHub - `GITHUB_ACTIONS`
- PM2 - `PM2_HOME`

or defaults `isTTY` in all CLI with supports output.

But there is nothing in CFW, ENV is clean, so it makes sense that it does not support color output.
This is a problem on CFW side.

## Workaround

Ansis supports the standard [environment variables](https://github.com/webdiscus/ansis/issues/24#cli-vars) such as `FORCE_COLOR` and and flags `--color`.

Before import the ansis, you can define in ENV the `FORCE_COLOR`.

The example from [cloudflare playground](https://workers.cloudflare.com/playground):
```js
import welcome from "welcome.html";

/**
 * @typedef {Object} Env
 */

export default {
	/**
	 * @param {Request} request
	 * @param {Env} env
	 * @param {ExecutionContext} ctx
	 * @returns {Promise<Response>}
	 */
	async fetch(request, env, ctx) {
                env.FORCE_COLOR = 1; // <= define FORCE_COLOR before to require/import of ansis
                const ansis = require('ansis');
                console.log('==> COLOR SUPPORT: ', ansis.isSupported());

		const url = new URL(request.url);
		console.log(`Hello ${navigator.userAgent} at path ${url.pathname}!`);

		if (url.pathname === "/api") {
			// You could also call a third party API here
			const data = await import("./data.js");
			return Response.json(data);
		}
		return new Response(welcome, {
			headers: {
				"content-type": "text/html",
			},
		});
	},
};
```

**Comment by louisgv** [comment]
Thanks for the triage! I ended up rolling out raw ascii coloring since we need only 5 colors xD
