### ISSUE TITLE
[Suggestions] Improving types and expose colours as named exports

### ISSUE THREAD

**Issue by panoply** [webdiscus/ansis#3]
I am leveraging ansis and appreciate the work you've done here but I have a couple of pain points and I'd like to suggest some minor refactors to improve how the module is used and generally just provide a better experience overall.

## Named Exports

The current approach is to have ansis export on the default but this is not always ideal. In order to obtain a single colour one needs to do the following:

```ts
import ansis from 'ansis';

console.log(`Print ${ansis.yellow('I am yellow')}`)
```
While this suffices, it can get a little cumbersome and a better option would be to provide an additional import/file that exposes the defaults as named exports, for example:

```ts
import { yellow } from 'ansis/colors';

console.log(`Print ${yellow('I am yellow')}`)
```

OR alternatively, you could expose the named exports directly and still preserve the default, eg: 
 
 ```ts
import ansis, { red } from 'ansis';

console.log(`Print ${ansis.yellow('I am yellow')} and ${red('I am red')}`)
```

Supporting this is trivial, you can simply add them to the exports, eg:

```js
// ....

const ansis = new Ansis();

export const {
  cyan,
  cyanBright,
  red,
  redBright,
  green,
  greenBright,
  yellow,
  yellowBright,
  magenta,
  magentaBright,
  blue,
  blueBright,
  white,
  whiteBright,
  gray,
  underline,
  bold,
  reset,
  italic,
  strike
  // etc etc etc
} = ansis;

export default ansis
``` 

## Improve Typings

It would be nice to have types available for additional usage. I have various functions which construct log output and accept colour parameters which I pass to ansis. In order for folks to take advantage of intellisense capabilities having a reference of the defaults would be a great help. Take the following sample:

```ts
import ansis from 'ansis'

export const write = (colour: string, message: string) => {
  message += fn(message) // do something 
  console.log(ansis[colour](message);
}
```
Currently, there is no exposed type refs for colors that ansis provides. Where the parameter `colour` expects a `string` a far better  approach is to have this available in the declaration, eg: 

```ts
import ansis, { Colors } from 'ansis' // using US english for the sake of brevity

export const write = (colour: Colors, message: string) => {
  message += fn(message) // do something 
  console.log(ansis[colour](message))
}
``` 

This is rather simple to provide, here is a starting point:

```ts
/**
 * Default Colors
 */
export type Colors = (
  | 'cyan'
  | 'cyanBright'
  | 'red'
  | 'redBright'
  | 'green'
  | 'greenBright'
  | 'yellow'
  | 'yellowBright'
  | 'magenta'
  | 'magentaBright'
  | 'blue'
  | 'blueBright'
  | 'white'
  | 'whiteBright'
  | 'gray'
  | 'underline'
  | 'bold'
  | 'reset'
  | 'italic'
  | 'strike'
  // etc etc etc
);
```

An even better approach would be:

```ts
type StringUnion<T, B extends string> = T | (B & Record<never, never>);

export type Colors = (
  | 'cyan'
  | 'cyanBright'
  | 'red'
  | 'redBright'
  | 'green'
  | 'greenBright'
  | 'yellow'
  | 'yellowBright'
  | 'magenta'
  | 'magentaBright'
  | 'blue'
  | 'blueBright'
  | 'white'
  | 'whiteBright'
  | 'gray'
  | 'underline'
  | 'bold'
  | 'reset'
  | 'italic'
  | 'strike'
  // etc etc
)

export type ColorsExtend<T extends string> = StringUnion<Colors, T>;
```

The above `ColorsExtend` would allow for consumers to extend the defaults with any custom colours generated in their projects, using the initial sample and the above types you could then do:

```ts
import ansis, { ColorsExtend } from 'ansis'

const pink = ansis.hex('#ff75d1');
const orange = ansis.hex('#FFAB40');

export const write = (colour: ColorsExtend<'pink' | 'orange'>, message: string) => {
  message += fn(message) // do something 
  console.log(ansis[colour](message))
}
```

Thanks

**Comment by webdiscus** [comment]
Hi,

thank you for an interesting suggestions.
I will certainly take the time to add your suggestions in new release.

Bests,
Dimitri

**Comment by panoply** [comment]
Great stuff, let me know if you need help.

**Comment by webdiscus** [comment]
Hi @panoply,

I have now time for this ticket and would like to clarify some questions.

What is your goal of `Named Exports`?

1.  `Named Exports` to save the size of imported code.
>  The unpacked dist code size is 3.1 KB only. Here is nothing to spare. And this module is so designed, that to export separate method is impossible, because each method (red, bold, hex, etc) is dynamic getter, not object property. This is the feature for the chained syntax.
> Therefore your suggestion can not work:
```js
export const {
  red,
  green,
  blue,
  // etc etc etc
} = ansis;
```

Also, my answer - no, is impossible.

2.  `Named Exports` for shortcuts to function name, e.g. using `red()` instead of `ansis.red()`.
The export could be in separate file `colors.js`:
```js
import ansis from './index.js';

export const red = ansis.red;
export const green = ansis.green;
export const blue = ansis.blue;
// etc.
```

Usage:

```js
import { red, green, blue } from 'ansis/colors';

console.log(red('red'));
console.log(green.bold('green'));
console.log(blue.underline.italic('blue'));
```
> **Note**
> - the ansis lib will be completely imported, you spare nothing
> - imported `shortcuts` supports chained syntax

Does it make sense to create the `colors.js` file with shortcuts for all styles when the package size will be even bigger?
I can do it, no problem, but whether make it sense for you?

**Comment by webdiscus** [comment]
@panoply 

yet two questions.

## 1. Type naming for  list of ANSI styles & colors

Your suggestion:
```ts
export type Colors = (
  | 'cyan'
  | 'cyanBright'
  // ...
)
type StringUnion<T, B extends string> = T | (B & Record<never, never>);
export type ColorsExtend<T extends string> = StringUnion<Colors, T>;
```

```ts
import ansis, { Colors, ColorsExtend } from 'ansis' 

const write = (style: ColorsExtend <'pink' | 'orange'>, message: string) => {
  console.log(ansis[style](message));
}
```

Yes, many ANSI libs use the type name `Colors`, but it is too common word and can be used by other libs working with colors.
To avoid naming collision I would suggest use specific naming, e.g. `AnsisColors`.
Commonly, the `red` `bgMagentaBright`, `bold` `invert` etc are not colors, otherwise are `ansi styles`.

What do you like as type name for list of ANSI styles & colors?
- AnsiColors (note: Ansi.., w/o (s) after `i`) / AnsiColorsExtend
- AnsiStyles (note: Ansi.., w/o (s) after `i`) / AnsiStylesExtend
- Colors / ColorsExtend
- Styles / StylesExtend
- your variant?

## 2. How to extend default colors in `ansis`?

Your example:
```ts
import ansis, { ColorsExtend } from 'ansis' 

const pink = ansis.hex('#FF75D1');
const orange = ansis.hex('#FFAB40');

const write = (style: ColorsExtend <'pink' | 'orange'>, message: string) => {
    console.log(ansis[style](message));
}
```

But how to use the `write` function?

```js
write('red', 'message'); // default style OK
write('pink', 'message'); // ERROR, the 'pink' style is not registered in 'ansis'
```
Do you have an idea how the `ansis` instance should be extended with new colors?
For example:
```js
/**
* @param {string} name
* @param {Ansis} style
*/
ansis.extend(name, style) {
}

// usage
const pink = ansis.hex('#FF75D1');
ansis.extend('pink', pink);

ansis.pink.bold('text');
ansis['pink']('text');
```

Solution that works right now:
```js
import ansis, { Ansis } from 'ansis' 

const pink = ansis.hex('#FF75D1'); // the instance of the Ansis interface

const write = (style: Ansis, message: string) => {
    console.log(style(message));
}

write(pink, 'message'); // OK
```

**Comment by webdiscus** [comment]
@panoply 
The v1.5.0 is deprecated, because has error in CommonJS mode. Use please fixed v1.5.1.

P.S. I use the rollup with plugins to build minified treeshaked distribution bundle. The `rollup-plugin-terser` compile very small bundle.js compatible with ECMA 2019 (last version supported by Node.js 12).
But thanks for tip, I look this tools.

**Comment by panoply** [comment]
@webdiscus great stuff here. 

Might be worth stripping literals, for example:

```js
import { green } from 'ansis/colors'

console.log(green`\n Hello World`) // Here we denote a newline character
```
Though personally not a issue for me, I'd assume folks would expect characters like `\n`, `\t` etc to be stripped or escaped with double slash, so the above sample, _should_ output (using ␊ to denote newline):

```
␊
Hello World
``` 
Opposed to 

```
\n Hello World
```

**Comment by webdiscus** [comment]
@panoply 

yes, you are right.

```js
green('Line-1\nLine-2')
```
output
```
Line-1
Line-2
```

But using template literals `` should be used native LF:
```
green`Line-1
Line-2`
```

output
```
Line-1
Line-2
```

I can't imagine that anybody will display `\n` `\t` as plain text in colour string.
**Contra**
- yet more code for 0.000000001% use cases
- lower performance with low ops/s
- other libraries do not it too

When this library has 1,000,000 downloads / month and many people would like this improvement, then yes, I would.
At the moment I don't see a sense do it. I have many other projects.

**Comment by webdiscus** [comment]
@panoply 

according  [Template literals Specifications](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), used `\n` will be expected as `\` and `n` chars in sting.

```js
tag`string text line 1 \n string text line 2`;
```

expected string
```
string text line 1 \n string text line 2
```

Therefore I will not break the Specifications ;-)

**Comment by panoply** [comment]
> I can't imagine that anybody will use \n \t in template string instead of native LF.

👌🏼 To reiterate, it is no issue for me personally, just confirming the intended design.

Thanks again for your brilliant work here. This project is both emancipating and a joy to leverage . These new capabilities have solidified it as breadwinner in the nexus (imo).

I'll go ahead and close this.

**Comment by webdiscus** [comment]
> [@webdiscus](https://github.com/webdiscus) great stuff here.
> 
> Might be worth stripping literals, for example:
> 
> import { green } from 'ansis/colors'
> 
> console.log(green`\n Hello World`) // Here we denote a newline character
> Though personally not a issue for me, I'd assume folks would expect characters like `\n`, `\t` etc to be stripped or escaped with double slash, so the above sample, _should_ output (using ␊ to denote newline):
> 
> ```
> ␊
> Hello World
> ```
> 
> Opposed to
> 
> ```
> \n Hello World
> ```

Three years later...

Hello @panoply,

I prepared a new `4.0.0-beta.16`, where added support for `\n`, `\t`, etc. in tagged template literals.

Ansis now treats tagged template literals the same way as normal strings, returning the same result as the standard function call.

Example with `\n` (newline, unescaped):
```js
red('prev\nnext')
red`prev\nnext`
```

Output:
```text
prev
next
```

Example with escaped backslash:
```js
red('prev\\next')
red`prev\\next`
```

Output:
```
prev\next
```

Here is the opened [discussion](https://github.com/webdiscus/ansis/discussions/35) about new major release v4.
